---
{{- if eq .Values.serviceAccount.create true }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- include "resource.name" .| nindent 2 }}
  labels:
    app.kubernetes.io/name: nginx-app
    app.kubernetes.io/instance: nginx
{{- end }}
