apiVersion: batch/v1
kind: Job
metadata:
  name: post-delete-job
  annotations:
    "helm.sh/hook": "post-delete"

spec:
  template:
    spec:      
      containers:
      - name: post-delete
        image: busybox
        imagePullPolicy: IfNotPresent
        
        command: ['sh', '-c', 'I am done with cleanup! ; sleep 5']
    
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 0
      
  backoffLimit: 3
  completions: 1
  parallelism: 1
